<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>sinc</string>
    <string>slaspec</string>
   </array>
  <key>name</key>
  <string>sleigh</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.sleigh</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#quotes</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#assigments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#operators</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#brackets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#export</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#branching</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#build</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#macro</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#define</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#token</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#attach</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#mnemonics</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#registers</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#cond_defines</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#hex</string>
        </dict>
       </array>
    </dict>
    <key>assigments</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\bis\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b=\b)</string>
          <key>name</key>
          <string>keyword.operator.assignment.c.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>attach</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\battach\b *)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bvariables\b)</string>
          <key>name</key>
          <string>keyword.control.module.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bnames\b)</string>
          <key>name</key>
          <string>keyword.control.module.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>brackets</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>([\(\{\[])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.sleigh</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#brackets__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>([\)\}\]])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.sleigh</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>brackets__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.sleigh</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>branching</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\bgoto\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bcall\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\breturn\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>build</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\bbuild\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>punctuation.definition.comment.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>cond_defines</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\@if)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\@elif)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\@endif)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>define</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\bdefine\b *)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\blocal\b *)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bif\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\binstruction\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bconst\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bunique\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\binst_start\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\binst_next\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bepsilon\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bregister\b)</string>
          <key>name</key>
          <string>keyword.control.module.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bcontext\b)</string>
          <key>name</key>
          <string>keyword.control.module.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bpcodeop\b)</string>
          <key>name</key>
          <string>keyword.control.module.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>export</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\bexport\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>hex</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(0x[a-fA-F0-9]*)</string>
          <key>name</key>
          <string>constant.numeric.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>macro</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\bmacro\b)([a-zA-Z]+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sleigh</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.module.sleigh</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>mnemonics</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(:\D\S*)</string>
          <key>name</key>
          <string>entity.function.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>operators</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(f?[\x{0021}\x{003d}]=)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{0026}\x{002f}\x{007c}\x{002f}\x{005e}]{1,2})</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{007e}\x{0021}])</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(f?[\x{002f}\x{002b}-\x{002f}\x{002a}])</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([fs]?[\x{002f}\x{002f}\x{0025}])</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([fs]?[\x{003c}\x{003e}]=?)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(s?&lt;{2}|s?&gt;{2}$)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>quotes</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.sleigh</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#quotes__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.sleigh</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>quotes__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.sleigh</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#quotes</string>
        </dict>
       </array>
    </dict>
    <key>registers</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([A-Za-z0-9_]*:?:\D)</string>
          <key>name</key>
          <string>keyword.other.unit.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>token</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\btoken\b)</string>
          <key>name</key>
          <string>keyword.control.module.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bsigned\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bhex\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bdec\b)</string>
          <key>name</key>
          <string>keyword.sleigh</string>
        </dict>
       </array>
    </dict>
    <key>types</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\bval\b)</string>
          <key>name</key>
          <string>storage.type.built-in.primitive.c.sleigh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\blocal\b)</string>
          <key>name</key>
          <string>storage.type.built-in.primitive.c.sleigh</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
